language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jalbacristian0493/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jalbacristian0493/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "sleepy-dragon"
  env: "SleepyDragon-env"
  bucket_name: "elasticbeanstalk-eu-west-2-206572730725"
  bucket_path: "sleepy-dragon"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY